/*
Static site generator for the doc system.

Emits one optimized, pre-rendered HTML file per doc at `/slug/index.html` (README
-> site root). Each page is complete without JavaScript — real <head> metadata, the
doc's markdown already rendered to HTML, and real <a> links to every other page —
then the <tosi-doc-system> element hydrates it into the interactive doc browser when
the IIFE bundle loads.

Build-time only (uses Bun.write). Shares slug + markdown rendering with the runtime
component (src/doc-system/*) so static and hydrated output agree.
*/

// NOTE: keep this module's imports limited to pure helpers (routing) and marked
// (render) plus type-only imports. Importing src runtime modules that the build
// regenerates (e.g. icons -> icon-data.ts) would put them in `bun --watch`'s graph
// and cause a rebuild loop. The theme stylesheet is generated by bin/generate-css.ts
// in a SEPARATE subprocess for exactly this reason.
import type { Doc } from './docs'
import type { ProjectLinks, LinkItem } from '../../doc-browser'
import { buildSlugMap, pathForSlug } from '../routing'
import { renderDocMarkdown, docDescription } from '../render'

declare global {
  var Bun: any
}

export interface GenerateSiteConfig {
  docs: Doc[]
  /** directory to write pages into (the served web root, e.g. ./docs) */
  outputDir: string
  projectName?: string
  /** site-level description, used as a fallback when a doc has none */
  description?: string
  /** <html lang>, default 'en' */
  lang?: string
  /** favicon href, default /favicon.svg */
  favicon?: string
  /** default og:image (per-page overridable via doc metadata) */
  ogImage?: string
  projectLinks?: ProjectLinks
  /** header-bar links (rendered as real <a> for no-JS, upgraded on hydration) */
  navbarLinks?: LinkItem[]
  /** translation table (TSV) for the settings menu's language picker */
  localizedStrings?: string
  /** URL the localization table is written to / loaded from (default /localized-strings.txt) */
  localizedUrl?: string
  /** absolute site origin for canonical/og URLs, e.g. https://ui.tosijs.net */
  baseUrl?: string
  /**
   * URL prefix the site is served under, default '/'. Set to '/<repo>' for a
   * GitHub project page without a custom domain; every root-relative URL the
   * generator emits is rewritten under it.
   */
  basePath?: string
  /** URL the component fetches the corpus from (default /docs.json) */
  docsUrl?: string
  /** path to the IIFE bundle script (default /iife.js) */
  scriptUrl?: string
  /** URL of the burned-in theme stylesheet (written by bin/generate-css.ts) */
  stylesUrl?: string
  /** extra lines injected into every <head> (favicon, analytics, etc.) */
  headExtra?: string
}

const escapeAttr = (s: string): string =>
  s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')

const escapeText = (s: string): string =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

/** Build the shared nav <ul> once; `currentFilename` gets aria-current. */
function navHtml(
  docs: Doc[],
  slugMap: Record<string, string>,
  currentFilename: string,
  basePath?: string
): string {
  const items = docs
    .map((doc) => {
      const href = withBase(basePath, pathForSlug(slugMap[doc.filename]))
      const current = doc.filename === currentFilename
      return `    <li><a href="${escapeAttr(href)}"${
        current ? ' aria-current="page" class="current"' : ''
      }>${escapeText(doc.title)}</a></li>`
    })
    .join('\n')
  return `  <nav class="doc-nav" aria-label="Documentation">\n  <ul>\n${items}\n  </ul>\n  </nav>`
}

/** Render a configurable link list (header bar or overflow menu) as crawlable HTML. */
function linkListHtml(className: string, links?: LinkItem[]): string {
  if (!links || links.length === 0) return ''
  const items = links
    .map(
      (link) =>
        `    <li><a href="${escapeAttr(link.href)}"${
          link.icon ? ` data-icon="${escapeAttr(link.icon)}"` : ''
        }>${escapeText(link.label)}</a></li>`
    )
    .join('\n')
  return `  <ul class="${className}">\n${items}\n  </ul>`
}

/** Serialize a JSON-LD object into a safe <script> (escaping `<` prevents breakout). */
function jsonLdScript(obj: Record<string, unknown>): string {
  return `  <script type="application/ld+json">${JSON.stringify(obj).replace(
    /</g,
    '\\u003c'
  )}</script>`
}

/** Absolute URL for an asset path against the site origin (passes through full URLs). */
function absUrl(baseUrl: string, pathOrUrl: string): string {
  if (!pathOrUrl) return ''
  return /^https?:\/\//.test(pathOrUrl) ? pathOrUrl : baseUrl + pathOrUrl
}

/**
 * Prefix a root-relative path with basePath. No-op for '/', empty, protocol-
 * relative (`//…`), or absolute (`https://…`) URLs.
 */
function withBase(basePath: string | undefined, p: string): string {
  if (!p || !basePath || basePath === '/' || /^(https?:)?\/\//.test(p)) return p
  return basePath.replace(/\/$/, '') + (p.startsWith('/') ? p : '/' + p)
}

function pageHtml(
  doc: Doc,
  config: GenerateSiteConfig,
  slugMap: Record<string, string>,
  configAttr: string
): string {
  const {
    projectName = '',
    baseUrl = '',
    lang = 'en',
    favicon = '/favicon.svg',
    docsUrl = '/docs.json',
    scriptUrl = '/iife.js',
    stylesUrl = '/doc-system.css',
    localizedUrl = '/localized-strings.txt',
    basePath,
    headExtra = '',
  } = config
  const localizedAttr = config.localizedStrings
    ? ` localized="${escapeAttr(withBase(basePath, localizedUrl))}"`
    : ''

  // `headTitle` is the verbatim <title>; otherwise suffix the project name (unless
  // the doc title already includes it).
  const title =
    doc.headTitle ||
    (projectName && !doc.title.includes(projectName)
      ? `${doc.title} — ${projectName}`
      : doc.title)
  // Per-page metadata (from the doc's JSON block) wins; else derive, else site default.
  const description =
    doc.description || docDescription(doc.text) || config.description || ''
  const keywords = Array.isArray(doc.keywords)
    ? doc.keywords.join(', ')
    : doc.keywords || ''
  const canonical =
    baseUrl + withBase(basePath, pathForSlug(slugMap[doc.filename]))
  const imageAbs = absUrl(
    baseUrl,
    withBase(basePath, doc.image || config.ogImage || '')
  )
  const body = renderDocMarkdown(doc.text)
  const nav = navHtml(config.docs, slugMap, doc.filename, basePath)
  const navbar = linkListHtml('doc-navbar', config.navbarLinks)

  const jsonLd = baseUrl
    ? jsonLdScript({
        '@context': 'https://schema.org',
        '@type': 'TechArticle',
        headline: doc.title,
        description,
        url: canonical,
        inLanguage: lang,
        ...(imageAbs ? { image: imageAbs } : {}),
        isPartOf: { '@type': 'WebSite', name: projectName, url: baseUrl },
      })
    : ''

  const head = [
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    // Render-blocking @import of web fonts lives in the stylesheet; warm the connection.
    '  <link rel="preconnect" href="https://fonts.googleapis.com" />',
    '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />',
    // Burned-in theme: styles the page with no JS and with zero flash on hydration.
    `  <link rel="stylesheet" href="${escapeAttr(
      withBase(basePath, stylesUrl)
    )}" data-tosi-doc-system />`,
    `  <title>${escapeText(title)}</title>`,
    description ? `  <meta name="description" content="${escapeAttr(description)}" />` : '',
    keywords ? `  <meta name="keywords" content="${escapeAttr(keywords)}" />` : '',
    doc.noindex ? '  <meta name="robots" content="noindex, follow" />' : '',
    baseUrl ? `  <link rel="canonical" href="${escapeAttr(canonical)}" />` : '',
    '  <meta property="og:type" content="article" />',
    projectName ? `  <meta property="og:site_name" content="${escapeAttr(projectName)}" />` : '',
    `  <meta property="og:title" content="${escapeAttr(title)}" />`,
    description ? `  <meta property="og:description" content="${escapeAttr(description)}" />` : '',
    baseUrl ? `  <meta property="og:url" content="${escapeAttr(canonical)}" />` : '',
    imageAbs ? `  <meta property="og:image" content="${escapeAttr(imageAbs)}" />` : '',
    `  <meta name="twitter:card" content="${imageAbs ? 'summary_large_image' : 'summary'}" />`,
    imageAbs ? `  <meta name="twitter:image" content="${escapeAttr(imageAbs)}" />` : '',
    jsonLd,
    `  <link rel="icon" href="${escapeAttr(withBase(basePath, favicon))}" />`,
    headExtra,
  ]
    .filter(Boolean)
    .join('\n')

  return `<!DOCTYPE html>
<html lang="${escapeAttr(lang)}">
<head>
${head}
</head>
<body>
  <tosi-doc-system docs="${escapeAttr(
    withBase(basePath, docsUrl)
  )}" config="${configAttr}"${localizedAttr}>
  <article class="doc-content">
${body}
  </article>
${nav}
${navbar}
  </tosi-doc-system>
  <script src="${escapeAttr(withBase(basePath, scriptUrl))}"></script>
</body>
</html>
`
}

export async function generateSite(config: GenerateSiteConfig): Promise<number> {
  const { docs, outputDir } = config
  const slugMap = buildSlugMap(docs)

  // Surface any slug collisions (the slug map disambiguates them, but a warning
  // tells the maintainer two docs share a base name).
  const seen = new Map<string, string>()
  for (const doc of docs) {
    const slug = slugMap[doc.filename]
    if (seen.has(slug)) {
      console.warn(
        `generate-site: slug "${slug}" used by both ${seen.get(slug)} and ${doc.filename}`
      )
    }
    seen.set(slug, doc.filename)
  }

  const configAttr = escapeAttr(
    JSON.stringify({
      projectName: config.projectName,
      projectLinks: config.projectLinks,
    })
  )

  // The theme stylesheet (config.stylesUrl) is written separately by
  // bin/generate-css.ts; pages here just <link> to it.

  let count = 0
  for (const doc of docs) {
    const slug = slugMap[doc.filename]
    const dir = slug === '' ? outputDir : `${outputDir}/${slug}`
    await Bun.write(`${dir}/index.html`, pageHtml(doc, config, slugMap, configAttr))
    count += 1
  }

  // The corpus the component fetches for nav + client-side rendering of other pages.
  await Bun.write(`${outputDir}/docs.json`, JSON.stringify(docs))

  // Translation table for the settings menu's language picker.
  if (config.localizedStrings) {
    const localizedPath = (config.localizedUrl || '/localized-strings.txt').replace(
      /^\//,
      ''
    )
    await Bun.write(`${outputDir}/${localizedPath}`, config.localizedStrings)
  }

  // sitemap.xml + robots.txt (needs an absolute origin for the URLs).
  if (config.baseUrl) {
    const urls = docs
      .filter((doc) => !doc.noindex)
      .map(
        (doc) =>
          `  <url><loc>${escapeText(
            config.baseUrl +
              withBase(config.basePath, pathForSlug(slugMap[doc.filename]))
          )}</loc></url>`
      )
      .join('\n')
    await Bun.write(
      `${outputDir}/sitemap.xml`,
      `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`
    )

    // Append a Sitemap line to robots.txt (already copied from static assets).
    const robotsPath = `${outputDir}/robots.txt`
    let robots = ''
    try {
      robots = await Bun.file(robotsPath).text()
    } catch {
      /* no robots.txt copied — start from a permissive default */
    }
    if (!robots.includes('Sitemap:')) {
      const base = robots.trim() ? robots.trim() + '\n' : 'User-agent: *\nAllow: /\n'
      await Bun.write(robotsPath, `${base}Sitemap: ${config.baseUrl}/sitemap.xml\n`)
    }
  }

  return count
}
